# Generated by Django 3.0.1 on 2020-01-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todo_models_date_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_models',
            name='date_todo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
