# Generated by Django 3.0.1 on 2020-01-01 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_auto_20200101_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_models',
            name='date_todo',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
